/** @type {import('tailwindcss').Config} */

// Tokens transcribed from the Stitch export
// (precision_analytical_system/DESIGN.md + the per-screen tailwind.config blocks).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      // Every colour is a CSS custom property so the whole system can be
      // repainted for dark mode from one place. The channels live in
      // src/index.css: :root carries light, .dark overrides it. Values are
      // space-separated RGB so Tailwind's /opacity modifiers still work.
      colors: {
        'outline': 'rgb(var(--outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'background': 'rgb(var(--background) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background) / <alpha-value>)',
        'surface': 'rgb(var(--surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant) / <alpha-value>)',
        'surface-tint': 'rgb(var(--surface-tint) / <alpha-value>)',
        'primary-hover': 'rgb(var(--primary-hover) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface) / <alpha-value>)',
        'primary': 'rgb(var(--primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--inverse-primary) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--secondary-fixed-dim) / <alpha-value>)',
        'on-secondary-fixed': 'rgb(var(--on-secondary-fixed) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--on-secondary-fixed-variant) / <alpha-value>)',
        'tertiary': 'rgb(var(--tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed': 'rgb(var(--on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--on-tertiary-fixed-variant) / <alpha-value>)',
        'error': 'rgb(var(--error) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container) / <alpha-value>)',
        'nav': 'rgb(var(--nav) / <alpha-value>)',
        'on-nav': 'rgb(var(--on-nav) / <alpha-value>)',
        'nav-deep': 'rgb(var(--nav-deep) / <alpha-value>)',
        'nav-raised': 'rgb(var(--nav-raised) / <alpha-value>)',
        'nav-hover': 'rgb(var(--nav-hover) / <alpha-value>)',
        'nav-active': 'rgb(var(--nav-active) / <alpha-value>)',
        'nav-line': 'rgb(var(--nav-line) / <alpha-value>)',
        'accent': 'rgb(var(--accent) / <alpha-value>)',
        'success': 'rgb(var(--success) / <alpha-value>)',
        'success-container': 'rgb(var(--success-container) / <alpha-value>)',
        'warning': 'rgb(var(--warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--on-warning-container) / <alpha-value>)',
        'danger': 'rgb(var(--danger) / <alpha-value>)',
        'danger-container': 'rgb(var(--danger-container) / <alpha-value>)',
        'chart-grid': 'rgb(var(--chart-grid) / <alpha-value>)',
        'chart-line': 'rgb(var(--chart-line) / <alpha-value>)',
        'chart-dot': 'rgb(var(--chart-dot) / <alpha-value>)',
        'chart-track': 'rgb(var(--chart-track) / <alpha-value>)',
        'chart-1': 'rgb(var(--chart-1) / <alpha-value>)',
        'chart-2': 'rgb(var(--chart-2) / <alpha-value>)',
        'chart-3': 'rgb(var(--chart-3) / <alpha-value>)',
        'chart-4': 'rgb(var(--chart-4) / <alpha-value>)',
        'scrollbar-thumb': 'rgb(var(--scrollbar-thumb) / <alpha-value>)',
        'scrollbar-thumb-hover': 'rgb(var(--scrollbar-thumb-hover) / <alpha-value>)',
        'drop-border': 'rgb(var(--drop-border) / <alpha-value>)',
        'drop-fill': 'rgb(var(--drop-fill) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
        card: '10px',
        full: '9999px',
      },
      // Loosened one step across the board. The comp packed 13px type into a
      // 6/12/16 rhythm; at 14px that reads as a wall, so gaps grow with it.
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '14px',
        lg: '20px',
        xl: '28px',
        gutter: '16px',
        rail: '228px',
        // The top bar height, shared with .fixed-canvas so the two screens that
        // pin to the viewport cannot drift out of step with it.
        topbar: '52px',
      },
      maxWidth: {
        'container-max': '1440px',
        'content-max': 'calc(1600px - 216px)',
      },
      fontFamily: {
        'page-title': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'section-title': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'kpi-value': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'label-bold': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        code: ['Geist', 'ui-monospace', 'monospace'],
        'body-main': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
      },
      // Sizes were transcribed from a 13px/11px comp and were too small to
      // read for long. The floor is now 14px body and 12px caption, and every
      // line-height sits near 1.5 so paragraphs and table rows breathe.
      fontSize: {
        'page-title': ['22px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'section-title': ['15px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'kpi-value': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-bold': ['13px', { lineHeight: '18px', fontWeight: '600' }],
        code: ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'body-main': ['14px', { lineHeight: '21px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        // The uppercase caption over a KPI value.
        'stat-label': ['11px', { lineHeight: '15px', letterSpacing: '0.07em', fontWeight: '600' }],
        'stat-value': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        ambient: '0px 1px 3px rgba(15, 23, 42, 0.08), 0px 4px 6px rgba(15, 23, 42, 0.05)',
      },
      keyframes: {
        'fade-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'none' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.97)' }, to: { opacity: '1', transform: 'none' } },
        'slide-in': { from: { opacity: '0', transform: 'translateX(12px)' }, to: { opacity: '1', transform: 'none' } },
        // Charts draw themselves in: the line is dashed by its own length and
        // the offset is walked back to zero.
        draw: { from: { strokeDashoffset: 'var(--draw-length, 1200)' }, to: { strokeDashoffset: '0' } },
        grow: { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        widen: { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        shimmer: { '100%': { transform: 'translateX(100%)' } },
        blink: { '50%': { opacity: '0' } },
      },
      animation: {
        'fade-up': 'fade-up 260ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in': 'fade-in 200ms ease-out both',
        'scale-in': 'scale-in 180ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in': 'slide-in 240ms cubic-bezier(0.16, 1, 0.3, 1) both',
        draw: 'draw 900ms cubic-bezier(0.16, 1, 0.3, 1) both',
        grow: 'grow 520ms cubic-bezier(0.16, 1, 0.3, 1) both',
        widen: 'widen 620ms cubic-bezier(0.16, 1, 0.3, 1) both',
        shimmer: 'shimmer 1.4s infinite',
        blink: 'blink 1s step-end infinite',
      },
    },
  },
  plugins: [],
}
